### ISSUE TITLE
 Cy7C185 Incompatible pins?

### ISSUE THREAD

**Issue by DanielTelles91** [btb/LanguageCard#3]
I am assembling the board but after analyzing the datasheet I noticed that the CY7C185 chip has a different pin position than the address line.
Can you please confirm if it is necessary to change the motherboard layout?

Thank you.

![Captura de tela 2024-10-10 011943](https://github.com/user-attachments/assets/f5c9f98b-2a6d-471c-b8b5-ff91f621218f)
![Captura de tela 2024-10-10 012001](https://github.com/user-attachments/assets/8db5569a-0f5b-4e50-8124-9ab447954f8b)

**Comment by btb** [comment]
That wouldn't make a difference- since every location is essentially the same, it's pretty much arbitrary how they are numbered. Of course it would matter if this were a ROM - if you programmed it on one system and then moved it to another system with different addressing, the data would be scrambled. 
Having said that - I know I bought some Cy7C185 chips to make sure it was 100% compatible, but I can't say for sure that I ever ended up testing those.
